### ISSUE TITLE
Is Tacchi able to simulate nonplanar surface tactile sensors? 

### ISSUE THREAD

**Issue by ElonMusk9577** [zixichen007115/Tacchi#1]
Is Tacchi able to simulate nonplanar surface tactile sensors?

**Comment by zixichen007115** [comment]
Yes. At least Tacchi can simulate the deformed surface of a soft sensor, but you need to define the relationship between surface and sensing values.

**Comment by ElonMusk9577** [comment]
> Yes. At least Tacchi can simulate the deformed surface of a soft sensor, but you need to define the relationship between surface and sensing values.

Thanks..
