### ISSUE TITLE
Contact Error

### ISSUE THREAD

**Issue by ElonMusk9577** [zixichen007115/Tacchi#2]
When the rigid indenter contacts with a soft pad, some of the pad particles fly out. What might have caused the error? (as shown in the figure behind) 
![contact error](https://github.com/zixichen007115/Tacchi/assets/37120404/9f28d521-a482-4fce-aec6-9c5ae4060721)

**Comment by zixichen007115** [comment]
The velocity of the rigid indenter may be too high. You can try to decrease the velocity.
If it doesn't work, could you please send me your code?

**Comment by YeahGrace** [comment]
I encountered the same problem when using MPM to simulate a rigid intender and a elastomer. Although I tried to decrease the velocity and decrease the number of particles, I still cannot solve it. Are there any other suggestions?
[https://github.com/YeahGrace/gel_MPM](url)

**Comment by zixichen007115** [comment]
First, I find that your code is quite different from mine. I suggest that you can try my code and adjust it according to your requirements.
Second, 3D GUI may also lead to some problems. You can try two 2D GUI windows, similar to my code.
