### ISSUE TITLE
type of data_len needs to be rectified in gel_press.py

### ISSUE THREAD

**Issue by gitouni** [zixichen007115/Tacchi#3]
# Bug
[Taichi] version 1.6.0, llvm 15.0.4, commit f1c6fbbd, linux, python 3.8.10
[Taichi] Starting on arch=cuda
744
Traceback (most recent call last):
  File "/home/ouni/CODE/Tactile/Tacchi/2_Tacchi_image_generation/gel_press.py", line 213, in <module>
    initialize(data, np.shape(data)[0], args.x, args.y)
  File "/home/ouni/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 976, in wrapped
    raise type(e)("\n" + str(e)) from None
taichi.lang.exception.TaichiTypeError: 
File "/home/ouni/CODE/Tactile/Tacchi/2_Tacchi_image_generation/gel_press.py", line 198, in initialize:
  for i in ti.ndrange(data_len):
           ^^^^^^^^^^^^^^^^^^^^
Every argument of ndrange should be an integer scalar or a tuple/list of (int, int)

# Solution:
change the type of data_len from `ti.f32` to `ti.i32`
```py
@ti.kernel
def initialize(data: ti.types.ndarray(),data_len: ti.i32, ind_x: ti.f32, ind_y: ti.f32):
  for i,j,k in ti.ndrange(num_l,num_w,num_h):
    m = i+j*num_l+k*num_l*num_w
    offest = ti.Vector([20-l/2,20-w/2,10-h/2])
    x[m] = ti.Vector([i,j,k])*dis+offest
    x_2d[m] = [x[m][0], x[m][1]]
    v[m] = [0, 0, 0]
    material[m] = 0
    F[m] = ti.Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
    C[m] = ti.Matrix.zero(float, 3, 3)
```

**Comment by zixichen007115** [comment]
Thank you for the issues. It's caused by different taichi versions. I will notice it.
