### ISSUE TITLE
Outliers need to be removed from the pcd

### ISSUE THREAD

**Issue by gitouni** [zixichen007115/Tacchi#4]
# Bug
Thanks for sharing your fantastic work. However, I observed outliers when I use the following snippet to view the pcd file.
```py
import os
import open3d as o3d
import numpy as np
from matplotlib import pyplot as plt
import time
def capture_img(vis):
    image = vis.capture_screen_float_buffer()
    plt.imsave(os.path.join(os.path.dirname(__file__),time.strftime("%H-%M-%S",time.localtime())+".png"),np.array(image))
    return False

def change_background_to_black(vis):
    opt = vis.get_render_option()
    opt.background_color = np.asarray([0, 0, 0])
    return False

def change_background_to_white(vis):
    opt = vis.get_render_option()
    opt.background_color = np.asarray([1, 1, 1])
    return False

def color_pcd(pcd):
    pts = np.array(pcd.points)
    N = pts.shape[0]
    colors = np.zeros([N, 3])
    height_max = np.max(pts[:, 2])
    height_min = np.min(pts[:, 2])
    delta_c = abs(height_max - height_min) / (255 * 2)
    color_n = (pts[:,2] - height_min)/delta_c
    mask = color_n <= 255
    n = mask.sum()
    color_n1 = 1-color_n[mask]/255  # (n,)
    color_n2 = color_n[~mask]/255 -1  # (N-n,)
    colors[mask,:] = np.hstack([np.zeros([n,1]),1-color_n1[:,None],color_n1[:,None],])
    colors[~mask,:] = np.hstack([color_n2[:,None],1-color_n2[:,None],np.zeros([N-n,1])])
    pcd.colors = o3d.utility.Vector3dVector(colors)
    return pcd

if __name__ == "__main__":
    pcd_path = "0_stl2npy/pcd/dot_in.pcd"
    pcd = o3d.io.read_point_cloud(pcd_path)
    pcd = color_pcd(pcd)
    key_to_callback = {}
    key_to_callback[ord(".")] = capture_img
    o3d.visualization.draw_geometries_with_key_callbacks([pcd],key_to_callback)
```
![image](https://github.com/zixichen007115/Tacchi/assets/30369762/e8f6208a-b658-43ec-86f5-b169972301fe)

# Solution
A simple solution would be to apply open3d outlier removal tool to exclude the outlier points.
Reference: 
[1]: [http://www.open3d.org/docs/release/tutorial/geometry/pointcloud_outlier_removal.html#Statistical-outlier-removal](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud_outlier_removal.html#Statistical-outlier-removal)
[2]: [http://www.open3d.org/docs/release/tutorial/geometry/pointcloud_outlier_removal.html#Radius-outlier-removal](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud_outlier_removal.html#Radius-outlier-removal)

The following snippet works for `dot_in.pcd`:
```py
pcd = o3d.io.read_point_cloud(pcd_path)
pcd = pcd.remove_radius_outlier(nb_points=16, radius=0.5)[0]
```
![image](https://github.com/zixichen007115/Tacchi/assets/30369762/9e26b102-c56e-4a6f-9c82-bd3d031b179a)
Hope I did not misread your codes and these distant scattered points are really outliers.

**Comment by zixichen007115** [comment]
Thank you for the issue. However, the shape of 'dot_in' in your result does not match the real shape, which is shown in '[README.md](https://github.com/zixichen007115/Tacchi#readme)'. There may be bugs in your visualization code.

**Comment by gitouni** [comment]
> Thank you for the issue. However, the shape of 'dot_in' in your result does not match the real shape, which is shown in '[README.md](https://github.com/zixichen007115/Tacchi#readme)'. There may be bugs in your visualization code.

Yes, my implementation of tranferring ply to pcd file is different from yours because [pcl_mesh_sampling](https://github.com/zixichen007115/Tacchi/blob/a56c44fba24a0d2a1dfcf123b9a559e23965b839/0_stl2npy/ply2pcd.py#L24) comand caused errors. Maybe this program relies on PCL. However, if you replace the pcd filepath with the ply filepath in the above code. In other words:
```py
pcd_path = "0_stl2npy/ply/dot_in.ply"
```
You will observe this outlier phenomenon.

**Comment by zixichen007115** [comment]
> > Thank you for the issue. However, the shape of 'dot_in' in your result does not match the real shape, which is shown in '[README.md](https://github.com/zixichen007115/Tacchi#readme)'. There may be bugs in your visualization code.
> 
> Yes, my implementation of tranferring ply to pcd file is different from yours because [pcl_mesh_sampling](https://github.com/zixichen007115/Tacchi/blob/a56c44fba24a0d2a1dfcf123b9a559e23965b839/0_stl2npy/ply2pcd.py#L24) comand caused errors. Maybe this program relies on PCL. However, if you replace the pcd filepath with the ply filepath in the above code. In other words:
> 
> ```python
> pcd_path = "0_stl2npy/ply/dot_in.ply"
> ```
> 
> You will observe this outlier phenomenon.

Thank you for mentioning that you change the ply2pcd method. I try your visualization with my pcd file, and it works. It seems that your pcd file does not contain all the dots. I will upload my pcd files soon, and I suggest you can try to do the ply2pcd transfer in my way.
![v](https://github.com/zixichen007115/Tacchi/assets/75701303/bcb5b77c-b4aa-410d-ad83-955e3e8ac852)

**Comment by gitouni** [comment]
Many thanks for your reply. I will try your advice later.

**Comment by zixichen007115** [comment]
> Many thanks for your reply. I will try your advice later.

btw, my wechat is chenzixi980730. We can contact on WeChat if you want.
